### ISSUE TITLE
AttributeError: 'set' object has no attribute 'items'

### ISSUE THREAD

**Issue by edoardoted99** [RohanDas28/Amazon-price-Tracker#2]
I run main.py after setting json and it returns this error:

pygame 2.0.0 (SDL 2.0.12, python 3.8.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 65, in <module>
    checking_price()
  File "main.py", line 32, in checking_price
    page = requests.get(URL, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 314, in prepare
    self.prepare_headers(headers)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 446, in prepare_headers
    for header in headers.items():
AttributeError: 'set' object has no attribute 'items'

**Comment by RohanDas28** [comment]
Checked it and fixed it.😉
